title: x-Qmo Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Ini adalah blog keren saya yang dibangun dengan Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "x-qmo.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username:  your_github

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
theme: null # Penting: Atur ke null karena kita membuat tema sendiri
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate

collections:
 # Contoh 1: Collection "team"

produk:
    output: true
    permalink: /produk/:path/ # ":path" akan menggunakan struktur folder dan nama file
